### PR TITLE
CDAP-13903

### PR DESCRIPTION
**Pull request by mattwuenschel**
Update runtime dir default value

### CODE REVIEW

**Comment by anwar6953** [comment]
Can you also update these two locations?
https://github.com/caskdata/cm_csd/blob/release/5.0/src/descriptor/service.sdl#L2580
https://github.com/caskdata/cm_csd/blob/release/5.0/src/descriptor/service.sdl#L2611

@gsps1 - can you also check if that's correct?

**Comment by mattwuenschel** [comment]
I checked on my CM cluster and the `${cdap.home}/master/ext/logging/config` doesn't exist.
`/opt/cdap/master/ext/logging/config` does exist but the directories are empty.

**Comment by anwar6953** [comment]
I think that's because CDAP creates those directories, based upon the configured value.

**Comment by gsps1** [comment]
yes, those directories are from `cdap-default` for config and library path for configuring additional logging pipelines. they will be empty by default.

**Pull request merged**
