### PR TITLE
Fixed usages of "CDAP Kafka" for metadata.

### PR DESCRIPTION
**Pull request by awholegunch**
Removed extra spaces after periods and before colons.

### CODE REVIEW

**Comment by awholegunch** [comment]
"On-hold", as there are comments in https://github.com/caskdata/cdap/pull/5143

**Comment by dereklwood** [comment]
:+1: LGTM but this is going to be hard to merge.  FYI it was in the style Cloudera uses but i'm fine changing it.

**Comment by dereklwood** [comment]
i resolved the conflicts... please doublecheck and merge PR

**Comment by awholegunch** [comment]
LGTM after a double-check.

**Pull request merged**
