### PR TITLE
Feature/4852 upgrade tool commands

### PR DESCRIPTION
**Pull request by dereklwood**
- [x] adds a new command to run the upgrade tool with ``upgrade_hbase`` argument
- [x] decided-upon labels, pls review the descriptions in particular.

### CODE REVIEW

**Comment by awholegunch** [comment]
Looks Pretty Good To Me, but a question: why are the descriptions and labels repeated? I can understand them appearing once, but why and when would the second set get used?

**Comment by awholegunch** [comment]
If you don't know the answer, perhaps run a test? Put something in the second set, and see how to trigger each?

**Comment by dereklwood** [comment]
one is at the cdap service level, the other is at the master role level. So they show up on either the CDAP service or master role pages. The cdap service one just invokes the other.

**Comment by dereklwood** [comment]
Updated again to include reminders to disable HBase tables, as I myself forgot to do it when verifying

**Comment by awholegunch** [comment]
LGTM.

**Pull request merged**
